windows: 
	g++ main.cpp client.cpp -o Paradoxia.exe -lws2_32 -lwininet -mwindows -m32 -lgdiplus -lwinmm

windows-static:
	g++ main.cpp client.cpp -o Paradoxia.exe -lws2_32 -lwininet -mwindows -static -m32 -lgdiplus -lwinmm
	
linux:
	i686-w64-mingw32-g++ main.cpp client.cpp -o Paradoxia.exe -lws2_32 -lwininet -mwindows -m32 -lgdiplus -lwinmm

linux-static:
	i686-w64-mingw32-g++ main.cpp client.cpp -o Paradoxia.exe -lws2_32 -lwininet -mwindows -static -m32 -lgdiplus -lwinmm
