#!/usr/bin/python3

"""

Have a good time reading the source. You are an amazing person.

"""
import sqlite3
import sys
import datetime

def get_text_data(database, output):
    strr = """
    LOGIN DATA TEXT ONLY
    CREATED AT {time}
    FROM 'LOGIN DATA' Database at : {path}
    ======================================
    """
    conn = sqlite3.connect(database) 
    cursor = conn.cursor()
    cursor.execute('Select action_url, username_value FROM logins')
    passfile = open(output, "w")
    passfile.write(strr.format(time=str(datetime.datetime.now()), path = database))
    for result in cursor.fetchall():
        passfile.write('\n\n[URL] '+result[0])
        passfile.write('\n[USER] '+result[1])


def __main__():
    try:
        database_path = sys.argv[1]
        output_file = sys.argv[2]
        print("[+] Will be Written to : " + output_file)
        get_text_data(database_path, output_file)
        print("[+] Done.")
    except IndexError:
        print("""
        LoginDataText 
        USAGE : ./LoginDataText < 'Login Data' file path > < output file name >
        Example : ./LoginDataText '/home/quantumcore/paradoxia/xx - xx/loot/Login Data' data.txt
        """)
        exit(True)
    except Exception as u:
        print("[X] Error : " + str(u))

if __name__ == '__main__':
    __main__()